name: FirstWorkflow
on: workflow_dispatch  # corrected from 'workflow_dispatcher'
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: |    #if we want to run multiple commands in one run 
           echo "HELLO WORLD"
           echo "I am learning git hub actions"
      - name: Create file 
        run: echo "Hello Anirudha file created"  > Anirudha.txt
